### ISSUE TITLE
Planificación de tiempos

### ISSUE THREAD

**Issue by MatiasDiAg** [MatiasDiAg/iw2016-tempojobs#3]
Esta tarea consta de los siguientes puntos principales:
- [x] Planificar tiempos de desarrollo.
- [x] Fases (Sprints).
- [x] Roles.
- [x] Reuniones.
- [x] Otros.

**Comment by MatiasDiAg** [comment]
Propuesta de roles asignados:
- Matías
  - Administrador de sistemas
  - Administrador de la base de datos
  - Codificador de pruebas
  - Analista/programador
- María
  - Jefe de proyecto
  - Arquitecto software
  - Diseñador de interfaz de usuario
  - Evaluador interno
  - Analista/programador

**Comment by MatiasDiAg** [comment]
Propuesta para reuniones:

30 mínutos una vez por semana para evaluar la dirección del proyecto.

**Comment by MatiasDiAg** [comment]
Planificación de sprints:
- Sprint 0:
  - Duración: 1 semana
  - Organización y planificación.
- Sprint 1: 
  - Duración: 1 semana
  - RF: 1.
- Sprint 2:
  - Duración: 2 semanas
  - RF: 2, 3 y 4.
- Sprint 3:
  - Duración: 1 semana
  - RF: 5 y 6.
- Sprint 4:
  - Duración: 1 semana
  - RF: 7 y 8
- Sprint 5:
  - Duración: 1 semana
  - RF: 9 y 10
- Sprint 6:
  - Duración: 1 semana
  - RF: 11

**Comment by mariamartinmarin** [comment]
Tareas finalizadas y listo el Entregable 1.
