### ISSUE TITLE
Preparar entorno de trabajo en local

### ISSUE THREAD

**Issue by MatiasDiAg** [MatiasDiAg/iw2016-tempojobs#4]
Cada uno debe tener instalado en su equipo los siguientes sistemas:
- [x]  IDE (STS y Spring Roo/gvNIX)
- [x] SGBD (MySQL)
- [x] Servidor de aplicaciones (Tomcat)
- [x] Sistema de control de versiones (Git)

**Comment by MatiasDiAg** [comment]
Cada miembro del grupo debe confirmar la instalación de los sistemas antes de cerrar la tarea.
- [x]  STS y Spring Roo/gvNIX
- [x] MySQL
- [x] Tomcat
- [x] Git

**Comment by mariamartinmarin** [comment]
Tengo todos los sistemas instalados. (STS y Spring Roo/gvNIX), MySQL, Tomcat y Git).
